import React, { useState } from 'react';
import { Sparkles, Heart, Wand2, Play, Download, Copy, Check, ExternalLink, RefreshCw, Send, Layers, Code, Eye } from 'lucide-react';
import { User } from '../types';
import ScrollControls from './ScrollControls';

interface LovableAIProps {
  user: User | null;
  onOpenAuth: () => void;
}

export default function LovableAI({ user, onOpenAuth }: LovableAIProps) {
  const [prompt, setPrompt] = useState('Create a modern SaaS dashboard with analytics charts, dark mode toggle, and active user metrics.');
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'code' | 'structure'>('preview');
  const [copied, setCopied] = useState(false);

  const [generatedApp, setGeneratedApp] = useState({
    title: 'Nova SaaS Analytics Pro',
    theme: 'Dark Violet & Emerald',
    components: ['Metric Cards', 'Revenue Growth Chart', 'Real-time User Activity', 'Quick Action Drawer'],
    htmlPreview: `
      <div class="p-6 bg-slate-900 text-white rounded-2xl border border-slate-800 font-sans">
        <div class="flex justify-between items-center pb-4 border-b border-slate-800">
          <div>
            <h1 class="text-xl font-black bg-gradient-to-r from-pink-400 to-indigo-400 bg-clip-text text-transparent">Nexus Pulse Dashboard</h1>
            <p class="text-xs text-slate-400">Autonomous SaaS Telemetry Engine</p>
          </div>
          <span class="px-3 py-1 bg-emerald-500/20 text-emerald-400 text-xs font-bold rounded-full border border-emerald-500/30">● 99.98% Healthy</span>
        </div>
        <div class="grid grid-cols-3 gap-3 my-4">
          <div class="p-3 bg-slate-800/80 rounded-xl border border-slate-700">
            <p class="text-[10px] text-slate-400 uppercase">Monthly Revenue</p>
            <p class="text-lg font-black text-emerald-400">$48,290</p>
            <p class="text-[10px] text-emerald-500">+14.2% this week</p>
          </div>
          <div class="p-3 bg-slate-800/80 rounded-xl border border-slate-700">
            <p class="text-[10px] text-slate-400 uppercase">Active Subscriptions</p>
            <p class="text-lg font-black text-indigo-400">1,420</p>
            <p class="text-[10px] text-indigo-300">89 new today</p>
          </div>
          <div class="p-3 bg-slate-800/80 rounded-xl border border-slate-700">
            <p class="text-[10px] text-slate-400 uppercase">AI API Quota</p>
            <p class="text-lg font-black text-pink-400">2.4M / 5M</p>
            <p class="text-[10px] text-pink-300">48% consumed</p>
          </div>
        </div>
        <div class="p-4 bg-slate-950/60 rounded-xl border border-slate-800 text-xs">
          <div class="flex justify-between items-center mb-2">
            <span class="font-bold text-slate-300">Live Traffic Stream</span>
            <span class="text-[10px] font-mono text-indigo-400">WebSocket Connected</span>
          </div>
          <div class="space-y-1.5 font-mono text-[11px] text-slate-400">
            <div class="flex justify-between"><span>[POST] /api/v2/checkout</span><span class="text-emerald-400">200 OK (42ms)</span></div>
            <div class="flex justify-between"><span>[GET] /api/v2/telemetry</span><span class="text-emerald-400">200 OK (18ms)</span></div>
            <div class="flex justify-between"><span>[POST] /api/v2/generate-ai</span><span class="text-purple-400">200 OK (210ms)</span></div>
          </div>
        </div>
      </div>
    `,
    code: `import React, { useState } from 'react';
import { BarChart, Activity, Users, DollarSign, ArrowUpRight } from 'lucide-react';

export default function AnalyticsDashboard() {
  const [timeRange, setTimeRange] = useState('7d');

  const metrics = [
    { label: 'Total Revenue', value: '$48,290', change: '+14.2%', icon: DollarSign, color: 'text-emerald-400' },
    { label: 'Active Users', value: '14,892', change: '+8.4%', icon: Users, color: 'text-indigo-400' },
    { label: 'Engine Requests', value: '2.4M', change: '+22.1%', icon: Activity, color: 'text-pink-400' }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <header className="flex justify-between items-center pb-6 border-b border-slate-800">
        <div>
          <h1 className="text-2xl font-bold bg-gradient-to-r from-pink-500 to-indigo-500 bg-clip-text text-transparent">
            Nexus Pulse
          </h1>
          <p className="text-sm text-slate-400">Autonomous Web App Generated by Lovable.ai</p>
        </div>
      </header>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-6">
        {metrics.map((m, i) => (
          <div key={i} className="p-5 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl">
            <span className="text-xs text-slate-400 font-semibold">{m.label}</span>
            <div className="text-2xl font-black mt-1 text-white">{m.value}</div>
            <div className="text-xs font-bold text-emerald-400 mt-2">{m.change} this period</div>
          </div>
        ))}
      </div>
    </div>
  );
}`
  });

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
    }, 1200);
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedApp.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-950 text-slate-100 overflow-hidden relative">
      <ScrollControls />
      {/* Header */}
      <div className="px-6 py-4 border-b border-white/5 bg-slate-900/60 backdrop-blur-md flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-pink-600 to-rose-500 flex items-center justify-center text-white shadow-lg shadow-pink-600/30">
            <Heart className="w-5 h-5 fill-white" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="font-display font-black text-base text-white">Lovable.ai Studio</h1>
              <span className="px-2 py-0.5 rounded-full bg-pink-500/20 text-pink-300 text-[10px] font-bold border border-pink-500/30 font-mono">
                Full-Stack App Builder
              </span>
            </div>
            <p className="text-xs text-slate-400">Natural language to production-ready React web apps</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyCode}
            className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-bold flex items-center gap-1.5 transition-all text-slate-200 border border-slate-700"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Export Code'}</span>
          </button>
        </div>
      </div>

      {/* Workspace */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden">
        {/* Left prompt & controls */}
        <div className="lg:col-span-5 border-r border-white/5 p-6 flex flex-col justify-between overflow-y-auto space-y-4">
          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                <Wand2 className="w-3.5 h-3.5 text-pink-400" />
                Prompt your web application
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={5}
                className="w-full p-4 rounded-2xl bg-slate-900 border border-slate-800 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-pink-500 resize-none font-sans"
                placeholder="Describe what you want to build (e.g., E-commerce store, CRM portal, AI chatbot UI)..."
              />
            </div>

            <div className="grid grid-cols-2 gap-2">
              {['SaaS Dashboard', 'AI Agent UI', 'Crypto Wallet', 'Social Network'].map((template) => (
                <button
                  key={template}
                  onClick={() => setPrompt(`Build a production ${template} with real-time analytics, responsive sidebar, and clean UI.`)}
                  className="p-2.5 rounded-xl bg-slate-900/80 hover:bg-pink-500/10 border border-slate-800 hover:border-pink-500/30 text-left text-xs font-medium text-slate-300 hover:text-pink-300 transition-all"
                >
                  ✨ {template}
                </button>
              ))}
            </div>

            <div className="p-4 rounded-2xl bg-pink-950/20 border border-pink-500/20 space-y-2">
              <span className="text-xs font-bold text-pink-300 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" /> Lovable Autonomous Engine
              </span>
              <p className="text-[11px] text-slate-400 leading-relaxed">
                Generates responsive Tailwind components, stateful hooks, icons from Lucide, and clean modular structures in seconds.
              </p>
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full py-3.5 px-4 rounded-xl bg-gradient-to-r from-pink-600 to-rose-600 hover:from-pink-500 hover:to-rose-500 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-lg shadow-pink-600/30 transition-all disabled:opacity-50 cursor-pointer"
          >
            {isGenerating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-white" />}
            <span>{isGenerating ? 'Synthesizing Architecture...' : 'Generate with Lovable.ai'}</span>
          </button>
        </div>

        {/* Right Preview / Code */}
        <div className="lg:col-span-7 flex flex-col bg-slate-950 overflow-hidden">
          {/* Subheader */}
          <div className="px-6 py-3 border-b border-white/5 bg-slate-900/40 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab('preview')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all ${
                  activeTab === 'preview' ? 'bg-pink-600 text-white' : 'text-slate-400 hover:text-white'
                }`}
              >
                <Eye className="w-3.5 h-3.5" /> Preview
              </button>
              <button
                onClick={() => setActiveTab('code')}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-all ${
                  activeTab === 'code' ? 'bg-pink-600 text-white' : 'text-slate-400 hover:text-white'
                }`}
              >
                <Code className="w-3.5 h-3.5" /> React Code
              </button>
            </div>

            <span className="text-[10px] font-mono text-slate-500">Live Hot-Reload Enabled</span>
          </div>

          {/* Tab Content */}
          <div className="flex-1 p-6 overflow-y-auto">
            {activeTab === 'preview' ? (
              <div className="h-full flex flex-col justify-center">
                <div dangerouslySetInnerHTML={{ __html: generatedApp.htmlPreview }} />
              </div>
            ) : (
              <pre className="p-4 rounded-2xl bg-slate-900 border border-slate-800 text-emerald-400 font-mono text-xs overflow-x-auto leading-relaxed">
                <code>{generatedApp.code}</code>
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
